//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace co.company.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class FacturaEncabezado
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FacturaEncabezado()
        {
            this.FacturaDetalle = new HashSet<FacturaDetalle>();
        }
    
        public int IdFacturaEncabezado { get; set; }
        public Nullable<int> IdCliente { get; set; }
        public string NumeroFactura { get; set; }
        public string CodigoEmpresa { get; set; }
        public string CodigoCliente { get; set; }
        public Nullable<float> sub_total { get; set; }
        public Nullable<float> impuesto { get; set; }
        public Nullable<float> Total { get; set; }
        public Nullable<System.DateTime> fechaFactura { get; set; }
    
        public virtual Clientes Clientes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FacturaDetalle> FacturaDetalle { get; set; }
    }
}
